<?php

$cst = array(
    'GEOIP_COUNTRY_EDITION' => GEOIP_COUNTRY_EDITION,
    'GEOIP_REGION_EDITION_REV0' => GEOIP_REGION_EDITION_REV0,
    'GEOIP_CITY_EDITION_REV0' => GEOIP_CITY_EDITION_REV0,
    'GEOIP_ORG_EDITION' => GEOIP_ORG_EDITION,
    'GEOIP_ISP_EDITION' => GEOIP_ISP_EDITION,
    'GEOIP_CITY_EDITION_REV1' => GEOIP_CITY_EDITION_REV1,
    'GEOIP_REGION_EDITION_REV1' => GEOIP_REGION_EDITION_REV1,
    'GEOIP_PROXY_EDITION' => GEOIP_PROXY_EDITION,
    'GEOIP_ASNUM_EDITION' => GEOIP_ASNUM_EDITION,
    'GEOIP_NETSPEED_EDITION' => GEOIP_NETSPEED_EDITION,
    'GEOIP_DOMAIN_EDITION' => GEOIP_DOMAIN_EDITION,
);

foreach ($cst as $k=>$v) {
    echo $k.': '.geoip_db_filename($v).'  '.(geoip_db_avail($v) ? 'Available':'')."\n";
}

print_r(geoip_record_by_name("195.135.221.4"));
